const COMMAND_TABLE = [
    [
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_lower_col_start_page, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_higher_col_start_page, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::set_mem_address_mode, arg_bytes: 1 },
        Command { function: CommandDecoder::set_col_address, arg_bytes: 2 },
        Command { function: CommandDecoder::set_page_address, arg_bytes: 2 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::cont_horiz_scroll_setup, arg_bytes: 6 },
        Command { function: CommandDecoder::cont_horiz_scroll_setup, arg_bytes: 6 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::cont_vert_horiz_scroll_setup, arg_bytes: 5 },
        Command { function: CommandDecoder::cont_vert_horiz_scroll_setup, arg_bytes: 5 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::deactivate_scroll, arg_bytes: 0 },
        Command { function: CommandDecoder::activate_scroll, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_start_line, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::set_contrast_control, arg_bytes: 1 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::set_charge_pump, arg_bytes: 1 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::set_segment_remap, arg_bytes: 0 },
        Command { function: CommandDecoder::set_segment_remap, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::set_vertical_scroll_area, arg_bytes: 2 },
        Command { function: CommandDecoder::entire_display_on, arg_bytes: 0 },
        Command { function: CommandDecoder::entire_display_on, arg_bytes: 0 },
        Command { function: CommandDecoder::set_normal, arg_bytes: 0 },
        Command { function: CommandDecoder::set_normal, arg_bytes: 0 },
        Command { function: CommandDecoder::set_multiplex_ration, arg_bytes: 1 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_on_off, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_on_off, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::set_page_start_address_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_page_start_address_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_page_start_address_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_page_start_address_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_page_start_address_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_page_start_address_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_page_start_address_page, arg_bytes: 0 },
        Command { function: CommandDecoder::set_page_start_address_page, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::set_com_output_scan_dir, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::set_com_output_scan_dir, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_offset, arg_bytes: 1 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::set_display_clock_ratio, arg_bytes: 1 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::set_precharge_period, arg_bytes: 1 },
        Command { function: CommandDecoder::set_com_pins_config, arg_bytes: 1 },
        Command { function: CommandDecoder::set_vcom_level, arg_bytes: 1 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::no_op, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
    ],
    [
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
        Command { function: CommandDecoder::illegal_command, arg_bytes: 0 },
    ],
];